export const PORT: 56700;
export const BROADCAST_ADDRESS: "255.255.255.255";
export const PRODUCTS_URL: "https://raw.githubusercontent.com/LIFX/products/master/products.json";
export type SERVICE_TYPE = number;
export namespace SERVICE_TYPE {
    let UDP: number;
    let RESERVED2: number;
    let RESERVED3: number;
    let RESERVED4: number;
    let RESERVED5: number;
}
export type TYPE = number;
export namespace TYPE {
    let GetService: number;
    let StateService: number;
    let GetHostFirmware: number;
    let StateHostFirmware: number;
    let GetWifiInfo: number;
    let StateWifiInfo: number;
    let GetWifiFirmware: number;
    let StateWifiFirmware: number;
    let GetPower: number;
    let SetPower: number;
    let StatePower: number;
    let GetLabel: number;
    let SetLabel: number;
    let StateLabel: number;
    let GetVersion: number;
    let StateVersion: number;
    let GetInfo: number;
    let StateInfo: number;
    let SetReboot: number;
    let Acknowledgement: number;
    let GetLocation: number;
    let SetLocation: number;
    let StateLocation: number;
    let GetGroup: number;
    let SetGroup: number;
    let StateGroup: number;
    let EchoRequest: number;
    let EchoResponse: number;
    let StateUnhandled: number;
    let GetColor: number;
    let SetColor: number;
    let SetWaveform: number;
    let LightState: number;
    let GetLightPower: number;
    let SetLightPower: number;
    let StateLightPower: number;
    let SetWaveformOptional: number;
    let GetInfrared: number;
    let StateInfrared: number;
    let SetInfrared: number;
    let GetHevCycle: number;
    let SetHevCycle: number;
    let StateHevCycle: number;
    let GetHevCycleConfiguration: number;
    let SetHevCycleConfiguration: number;
    let StateHevCycleConfiguration: number;
    let GetLastHevCycleResult: number;
    let StateLastHevCycleResult: number;
    let SetColorZones: number;
    let GetColorZones: number;
    let StateZone: number;
    let StateMultiZone: number;
    let GetMultiZoneEffect: number;
    let SetMultiZoneEffect: number;
    let StateMultiZoneEffect: number;
    let SetExtendedColorZones: number;
    let GetExtendedColorZones: number;
    let StateExtendedColorZones: number;
    let GetRPower: number;
    let SetRPower: number;
    let StateRPower: number;
    let GetDeviceChain: number;
    let StateDeviceChain: number;
    let Get64: number;
    let State64: number;
    let Set64: number;
    let GetTileEffect: number;
    let SetTileEffect: number;
    let StateTileEffect: number;
    let SensorGetAmbientLight: number;
    let SensorStateAmbientLight: number;
}
export const NO_TARGET: Uint8Array;
